import React from "react";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import { getMovies } from "../src/services/get-movies";
import { Languages } from "../src/typings/translation";
import { IMovie } from "../src/typings/movie";
import Link from "next/link";
import { useRouter } from "next/router";

interface IHomeProps {
  popularMovies: IMovie[];
  topRatedMovies: IMovie[];
  upcomingMovies: IMovie[];
}

export const getStaticProps: GetStaticProps<IHomeProps> = async ({
  locale,
}) => {
  const popularMovies = await getMovies(
    (locale || "en-US") as Languages,
    "popular"
  );
  const topRatedMovies = await getMovies(
    (locale || "en-US") as Languages,
    "top_rated"
  );
  const upcomingMovies = await getMovies(
    (locale || "en-US") as Languages,
    "upcoming"
  );

  return {
    props: {
      popularMovies,
      topRatedMovies,
      upcomingMovies,
    },
  };
};

const Home: NextPage<IHomeProps> = ({
  popularMovies,
  topRatedMovies,
  upcomingMovies,
}) => {
  const [movies, setMovies] = React.useState<IMovie[]>(popularMovies);

  const { locale } = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {movies.map((movie) => (
          <li key={movie.id}>
            <Link
              href={`/movie/${movie.id}`}
              as={`/movie/${movie.id}`}
              locale={locale}
            >
              <a>{movie.title}</a>
            </Link>
          </li>
        ))}
      </main>
    </div>
  );
};

export default Home;
